// RootLayout

import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header";

//Seo reads metadata
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Header />

        <main className="p-5">
          {/* Children in next -> Outlet in react/ To render child routes*/}
          {children}
        </main>
        
      </body>
    </html>
  );
}
